### ISSUE TITLE
Where do we show the outputs??

### ISSUE THREAD

**Issue by rkulshreshtha** [vijaykiran225/Scrabble_Group1#2]
Do we have to output the words in file or on the compiler window itself??

**Comment by jbhavana** [comment]
I think showing on the console is fine.

**Comment by SoumyajyotiBanerjee** [comment]
Console is fine but creating file is safe for large inputs and inputs with higher number of spaces.

**Comment by vijaykiran225** [comment]
i'm going with console for now... update it later if needed
