### ISSUE TITLE
In Scrabble.java for the function sort_word_byScore : why we are not checking that if the letter is '*' or not??

### ISSUE THREAD

**Issue by SoumyajyotiBanerjee** [vijaykiran225/Scrabble_Group1#6]
before int char_index = (int)word.charAt(i) % 'a';

if we suppose to get word with alphabets only?? otherwise we can make it

if(word.charAt(i)!='*')
{
    int char_index = word.charAt(i) - 'a';  
}

**Comment by vijaykiran225** [comment]
put the 'a' as an constant so that it can be changed later
